deployment:
  tasks:
    # Define the deployment path to your cPanel public directory
    - export DEPLOYPATH=/home/cgrithy/public_html/demo/

    # Copy all files and folders (including hidden ones) recursively from the current workspace to the deployment directory
    - /bin/cp -R * $DEPLOYPATH

    # (Optional) Copy hidden files (like .env, .htaccess) if necessary
    - /bin/cp -R .* $DEPLOYPATH
